# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-01 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userOperation', '0014_auto_20180709_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodels',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='FeedBackModels/%y/%d/10fb684e4a14453bbb8080d0bdacfe39', verbose_name='反馈图片'),
        ),
        migrations.AlterField(
            model_name='sysmessages',
            name='ISOPEN',
            field=models.CharField(choices=[('1', '已读'), ('0', '未读')], default='0', max_length=1, verbose_name='是否已读'),
        ),
    ]
