# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-01 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagess', '0003_auto_20180709_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysusermodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='SysUserModel/%Y/%m/214b961783794902aba5f1a7a5d44e91', verbose_name='系统用户头像'),
        ),
    ]
